### ISSUE TITLE
Medaka Model

### ISSUE THREAD

**Issue by llk578496** [epi2me-labs/wf-bacterial-genomes#1]
Hi

May I know what are the `medaka models` that being supported in this pipeline?

Thank you!

**Comment by cjw85** [comment]
Hi @llk578496,

The pipeline is currently set up to use a slightly older version of medaka but should support all variant calling models in the most recent version of medaka.

The project needs a bit of a refresh to update the command-line interface in line with the standards of our other workflows.

**Comment by sarahjeeeze** [comment]
Closing through lack of response.
