### ISSUE TITLE
[Question]: no gbk output files for the newest version?

### ISSUE THREAD

**Issue by lagphase** [epi2me-labs/wf-bacterial-genomes#14]
### What happened?

Hi, 
The newest version generates gff output file but not gbk file anymore (which is not really helpful). Is there an option for gbk output file? Thanks.

### Operating System

Windows 10

### Workflow Execution

EPI2ME Labs desktop application

### Workflow Execution - CLI Execution Profile

None

### Workflow Version

0.3.0

### Relevant log output

```shell
||||||||||   _____ ____ ___ ____  __  __ _____      _       _
||||||||||  | ____|  _ \_ _|___ \|  \/  | ____|    | | __ _| |__  ___
|||||       |  _| | |_) | |  __) | |\/| |  _| _____| |/ _` | '_ \/ __|
|||||       | |___|  __/| | / __/| |  | | |__|_____| | (_| | |_) \__ \
||||||||||  |_____|_|  |___|_____|_|  |_|_____|    |_|\__,_|_.__/|___/
||||||||||  wf-bacterial-genomes v0.3.0-g0d2379f
```

**Comment by sarahjeeeze** [comment]
Hi, Thanks for this feedback. We will consider adding this back in the near future.

**Comment by lagphase** [comment]
Yes please add it back and keep things consistent.

What is the revision of the v0.2.14? I want to revert the latest version to this one. Thanks.

**Comment by cjalder** [comment]
Hi,

The latest version of the workflow `v0.3.1` now outputs both the GBK and GFF files.

Thanks for highlighting the issue.
