### ISSUE TITLE
Use `-profile docker` instead of `-profile standard` when using Docker

### ISSUE THREAD

**Issue by tavareshugo** [epi2me-labs/wf-bacterial-genomes#16]
### Is your feature related to a problem?

At the moment, for using _Docker_, one needs to run the workflow with `-profile standard`. 
It might be more intuitive for users to use `-profile docker` to do this instead, which is the standard used by `nf-core` pipelines. 

### Describe the solution you'd like

I believe this could be done by changing the [current config file](https://github.com/epi2me-labs/wf-bacterial-genomes/blob/e223e1b85bd301fd73cac520048ac2d1fbd5f82a/nextflow.config#L102) to use something closer to what nf-core pipelines use ([example here](https://github.com/nf-core/rnaseq/blob/3bec2331cac2b5ff88a1dc71a21fab6529b57a0f/nextflow.config#L145)).

### Describe alternatives you've considered

Adding clearer documentation about the default behaviour to the README (and possibly the `--help` page) could be an alternative. At the moment this has to be inferred from the config source. 

### Additional context

(and thank you for all the work in developing these pipelines!)

**Comment by cjalder** [comment]
Hi,

The workflow will use the `standard` profile by default (i.e for use with Docker) so you do not need to use the `-profile` param if you want to use Docker. However, if this not the case for you please let us know!

We'll review our READMEs/Documentation to understand how to better inform users on these behaviours within the workflows!

**Comment by tavareshugo** [comment]
Hi @cjalder, thanks for your reply.

I understand that is the default behaviour, but I just thought it would be nice to make it clearer in the docs (as I'm used to nf-core pipelines, I didn't expect that would be the default behaviour). 

The README currently says: 

> The workflow can currently be run using either Docker or Singularity to provide isolation of the required software. Both methods are automated out-of-the-box provided either Docker or Singularity is installed.

Maybe a simple change would be (in bold): 

> The workflow can currently be run using either Docker **(default)** or Singularity **(`-profile singularity`)** to provide isolation of the required software. Both methods are automated out-of-the-box provided either Docker or Singularity is installed.

I think that would have been enough for an nf-core user such as myself to not automatically assume I should run the pipeline with `-profile docker`.

**Comment by mattdmem** [comment]
Thanks @tavareshugo,

We'll update the docs in an upcoming version.

Matt
