### ISSUE TITLE
Got "No disjointigs were assembled" error when running denovo

### ISSUE THREAD

**Issue by bsalehe** [epi2me-labs/wf-bacterial-genomes#17]
I have tried to run the pipeline with single ONT sample on WSL2 with singularity profile _denovo_ i.e. running with flye assembler. The sample appears to have high coverage. It is from bacteria with 4mb genome size.  Further investigation in the .nexflow.log file indicated it is a flye related error which seemed to be the case as reported [here](https://github.com/fenderglass/Flye/issues/128).

 I manually configured the flye command in the 'main.nf' file by adding the `--asm-coverage` and `--genome-size` options which didn't throw that error anymore only threw a memory error.

Would it be convenient to add in the advanced options additional parameters in the pipeline for running flye like it is recommended [here](https://github.com/fenderglass/Flye/issues/128#issuecomment-506509828) in a similar way you hva done for running prokka or medaka which are available in the pipeline usage help (`nextflow run epi2me-labs/wf-bacterial-genomes --help`)?

Note:
The solution given in the flye issue above require to add additional paramter `--genome-size <value>` as shoen in the current flye usage [doc](https://github.com/fenderglass/Flye/blob/flye/docs/USAGE.md#-quick-usage).

Thank you!

**Comment by cjalder** [comment]
Hi @bsalehe thanks for raising this. We'll try and implement these for a future update. 

In regards to the memory issue, you can pass a config file to increase the memory (if your machine has more resources available) by following the instructions in this [issue.](https://github.com/epi2me-labs/wf-bacterial-genomes/issues/12)
