### ISSUE TITLE
Workflow execution completed unsuccessfully! Error executing process > 'calling_pipeline:medakaNetwork (2)'

### ISSUE THREAD

**Issue by Lenfera** [epi2me-labs/wf-bacterial-genomes#19]
### Ask away!

Hello Epi2me labs team,

We tried to run the workflow 'bacterial genome' within an oracle VM with Ubuntu 22.04.3 LTS 64-bit in the Epi2me labs desktop application.
To check if it works, we tried 'Use Demo Data'

We had this report :

Workflow execution completed unsuccessfully!
The exit status of the task that caused the workflow execution to fail was: 134.

The full error message was:

Error executing process > 'calling_pipeline:medakaNetwork (2)'

Caused by:
  Process `calling_pipeline:medakaNetwork (2)` terminated with an error exit status (134)

Command executed:

  medaka --version
      echo r1041_e82_400bps_sup_v4.2.0
  
      echo r1041_e82_400bps_sup_v4.2.0
  
      medaka consensus align.bam "test1.consensus_probs.hdf"         --threads 2 --regions "NC_000962.3:999000-1999000
  " --model r1041_e82_400bps_sup_v4.2.0

Command exit status:
  134

Command output:
  medaka 1.9.1
  r1041_e82_400bps_sup_v4.2.0
  r1041_e82_400bps_sup_v4.2.0

Command error:
  Cannot import pyabpoa, some features may not be available.
  medaka 1.9.1
  r1041_e82_400bps_sup_v4.2.0
  r1041_e82_400bps_sup_v4.2.0
  The TensorFlow library was compiled to use AVX instructions, but these aren't available on your machine.
  .command.sh: line 8:    90 Aborted                 (core dumped) medaka consensus align.bam "test1.consensus_probs.hdf" --threads 2 --regions "NC_000962.3:999000-1999000
  " --model r1041_e82_400bps_sup_v4.2.0

Work dir:
  /home/sprzto/epi2melabs/instances/wf-bacterial-genomes_01HBGHJP7JQSFKRC9P6QD7WTJK/work/72/fb42aff10d6ba33fdc644968b2c3ff

Tip: you can replicate the issue by changing to the process work dir and entering the command `bash .command.run`

I tried this : https://github.com/tensorflow/tensorflow/issues/24548
(mehdirezaie commented on Mar 27, 2020)

But we still have the same error.
What could we do to solve this ?

**Comment by cjw85** [comment]
Please reopen this issue using the more appropriate Bug Report issue template. It helps us to help you.
