### ISSUE TITLE
bakta instead of prokka

### ISSUE THREAD

**Issue by splaisan** [epi2me-labs/wf-bacterial-genomes#23]
### Is your feature related to a problem?

I recently [read from the Prokka author himself Torsten Seemann](https://twitter.com/torstenseemann/status/1565471892840259585) that [Bakta](https://github.com/oschwengers/bakta) would now be a better option to annotate bacterial genome as it is better maintained.

### Describe the solution you'd like

Would it be possible to add bakta to the pipeline and make this an option for those who want to stick to prokka?

### Describe alternatives you've considered

none for bacterial genomes but for bacterio-phages there is also [pharokka](https://github.com/gbouras13/pharokka) which makes an incredible good job.

### Additional context

thanks in advance for considering this (these)

**Comment by cjw85** [comment]
This is on our roadmap; we were actually going to make the change for other reasons.

**Comment by fraser-combe** [comment]
This would be a great addition

**Comment by mattdmem** [comment]
We're working on this so I'm closing this issue for now. Check back soon @fraser-combe and we should have implemented bakta!
