### ISSUE TITLE
Dorado models v4.3.0

### ISSUE THREAD

**Issue by lagphase** [epi2me-labs/wf-bacterial-genomes#25]
### Ask away!

Hi,

Could you update the workflow to integrate the new Medaka configuration for Dorado basecalling dna_r10.4.1_e8.2_400bps@v4.3.0 ?

Thank you.

**Comment by cjalder** [comment]
Hi @lagphase - Thanks for highlighting, we will try and address this soon!

**Comment by julibeg** [comment]
hi @lagphase, the basecalling and medaka models have been updated with v1.3.0. The update also introduced automatic model selection and retired the `--basecaller_cfg` parameter.

I am closing this issue for now. Please feel free to re-open it if you run into the same problem with the most recent version of the workflow.
