### ISSUE TITLE
Information about circular contigs

### ISSUE THREAD

**Issue by frumencelab** [epi2me-labs/wf-bacterial-genomes#27]
### Is your feature related to a problem?

The wf-bacterial-genomes workflow enables the reconstruction of circular genomes and plasmids. In the report, the number of circular contigs is indicated. However, it is difficult to determine which contigs are circular and which are linear. It seems that this information is not provided in the report, nor in the .gbk or fasta.gz files. It is necessary to delve into the 'work' directory and locate the flye_stats.tsv file to determine whether a contig is circular or not. 

### Describe the solution you'd like

Would it be possible to indicate in the report which contigs are circular? 

### Describe alternatives you've considered

Furthermore, could this information be included in the .gbk file? Currently, all circular contigs are identified as linear in the GBK file.

Thank you in advance for your help.

Sincerly

Etienne

**Comment by cjalder** [comment]
Hi @frumencelab, thanks for highlighting this issue. We'll have a look at how best to report the circular contigs in the assembly and fixing the GBK output.

**Comment by cjalder** [comment]
Hi @frumencelab - Just to say this is now available in the report in  v1.4.1
