### ISSUE TITLE
Output  improvements

### ISSUE THREAD

**Issue by fraser-combe** [epi2me-labs/wf-bacterial-genomes#32]
### Is your feature related to a problem?

Show more options for workflow rather than run in nextflow command line. At the moment you can only select input and reference file

Output is limited in Report

Zoom buttons do not work correctly in report charts

### Describe the solution you'd like

It would be useful to see an output of the lengths of each contig from Flye assemblies

MLST output - it would be useful to obtain an output if MLST analysis was successful or failed as no output is not very informative

### Describe alternatives you've considered

Run Brakta instead of Prokka

**Comment by cjalder** [comment]
Hi @fraser-combe, thanks for raising this. To address your points:
- `nextflow run epi2me-labs/wf-bacterial-genomes --help` should give you a more detailed look into the parameters you can use in the workflow, or the [README's input parameters](https://github.com/epi2me-labs/wf-bacterial-genomes?tab=readme-ov-file#input-parameters) section should highlight these.
- We are looking to improve the assembly stats for the report for more details information on the Flye assemblies
- MLST is only run in `--isolates` mode, and should appear in the report if it has passed or fail like in the example image below 
![mlst_example_report](https://github.com/epi2me-labs/wf-bacterial-genomes/assets/38727026/20595b34-7810-4ffa-8a24-4fd33a551da9)
- We are working on replacing prokka with bakta.

**Comment by fraser-combe** [comment]
I do get errors when running the nextflow command, 

╰─ nextflow run epi2me-labs/wf-bacterial-genomes –-help

N E X T F L O W  ~  version 23.10.1
Launching `https://github.com/epi2me-labs/wf-bacterial-genomes` [chaotic_joliot] DSL2 - revision: 6af54574c3 [master]
WARN: NEXTFLOW RECURSION IS A PREVIEW FEATURE - SYNTAX AND FUNCTIONALITY CAN CHANGE IN FUTURE RELEASES

ERROR ~ Validation of pipeline parameters failed!

 -- Check '.nextflow.log' file for details
ERROR ~ * Missing required parameter: --fastq

 -- Check '.nextflow.log' file for details
