### ISSUE TITLE
Basecalling options not included in basecaller.cfg.

### ISSUE THREAD

**Issue by YoungMunLEE** [epi2me-labs/wf-bacterial-genomes#34]
### Ask away!

The latest version uses dna_r10.4.1_e8.2_400bps_sup@v4.3.0 for basecalling with MinKNOW. 
However, there are currently no available options to select. The latest version available is v4.2.0. What should be done in this case?
![image](https://github.com/epi2me-labs/wf-bacterial-genomes/assets/128474904/43941096-928d-4270-bbfe-b075e1e6c7bc)

**Comment by julibeg** [comment]
Hi @YoungMunLEE,

Thank you for bringing this to our attention. The list of available models will be updated with the next release.

**Comment by julibeg** [comment]
Hi @YoungMunLEE,

This was updated in v1.3.0, which also retired the `--basecaller_cfg` parameter (as on recently basecalled data the workflow should now be able to detect the basecall model automatically).

I'm closing this issue for now; please feel free to re-open if you run into the same problem with the most recent version.
