### ISSUE TITLE
Flye circular prediction

### ISSUE THREAD

**Issue by VICTO160** [epi2me-labs/wf-bacterial-genomes#37]
### Is your feature related to a problem?

no

### Describe the solution you'd like

Can either the flye_stats.tsv file be saved in the output file, or the contigs be reported as circular/linear in the HTML file output.

### Describe alternatives you've considered

Manually copying file out of intermediate subdirectories.

**Comment by cjalder** [comment]
@VICTO160 Thanks for raising this. Its a hotly requested feature so we'll be working on adding it to the next release!

**Comment by angelovangel** [comment]
Just publishing the flye_stats.tsv would be great..
I still dont understand why is this not published, as this is the point of the whole pipeline

**Comment by cjalder** [comment]
Hi both - sorry for the delay. This should now be in the report in v1.4.1, with the flye stats tsv also being outputted
