### ISSUE TITLE
From basecalling to error correction (Fastq to Fasta) as input to wf-bacterial genome

### ISSUE THREAD

**Issue by jibrantahir** [epi2me-labs/wf-bacterial-genomes#42]
### Ask away!

Hi 
I want to ask that downstream from base calling we do error-correction using dorrado , the step which convert fastq to fasta. However in wf-bacterial workflow we directly use fastq. Which fastq is it - uncorrected. And can we use fasta as input.
Many thanks

**Comment by cjalder** [comment]
Hi @jibrantahir - we use the uncorrected fastq directly from dorado for the workflow. There are currently on plans for a FASTA input for the workflow.
