### ISSUE TITLE
Can unclassified bams from basecalling which could not be demultplexed, be of some use in reference based assembly

### ISSUE THREAD

**Issue by jibrantahir** [epi2me-labs/wf-bacterial-genomes#43]
### Ask away!

Hi
When we basecall and demultiplex our pod5 reads, there are some unclassified bam piled up in one file. It still has reads but could not be demultiplexed. Is there a way to still utilize them- for example in a reference based assembly scenario, can we use them?
Thank you

**Comment by cjalder** [comment]
Hi @jibrantahir - I would not advise using reads from the unclassified folder as you do not know which barcode they belong to, so the chance of cross-contamination is high.
