### ISSUE TITLE
Barcode trimming

### ISSUE THREAD

**Issue by kevinbretscher** [epi2me-labs/wf-bacterial-genomes#49]
### Ask away!

Hi, 

We are currently following the [NO-MISS protocol](https://nanoporetech.com/document/no-miss-isolate-sequencing-rapid-barcoding-v14) from nanopore. According to their protocol we leave the Minknown settings at default. In this case barcodes will not be trimmed from the FastQ files. Following their workflow they go straight from the raw data to the bacteria genomes pipeline. 

I am not sure if this pipeline trims the barcodes and if it is neccesary at all? Is there any information on this?

**Comment by cjalder** [comment]
Hi @kevinbretscher - The Flye assembler doesn't do barcode trimming for the assembly process, but it does account for lower accuracy read ends, which would include the barcode and adapter in your data.
