### ISSUE TITLE
[Bug]: program doesn't run

### ISSUE THREAD

**Issue by matteo1313** [epi2me-labs/wf-bacterial-genomes#7]
### What happened?

First off thank you for this great program <3

The program unfortunately does not run. I have attached the screenshot of my termainal to show the error message that I am getting. It says this:
No such variable: Exception evaluating property 'out' for nextflow.script.ChannelOut, Reason: groovy.lang.MissingPropertyException: No such property: out for class: groovyx.gpars.dataflow.DataflowBroadcast

Thank you for the help!

![Screenshot from 2023-04-27 09-01-50](https://user-images.githubusercontent.com/81880944/234920542-eac6b603-e1e4-4547-b68e-72140c6e26d5.png)

### Operating System

ubuntu 20.04

### Workflow Execution

Command line

### Workflow Execution - CLI Execution Profile

None

### Workflow Version

0.2.5

### Relevant log output

```shell
There is no log output in my output directory.
```

**Comment by sarahjeeeze** [comment]
Hi, Looks like your local pull and the version you are running are not in sync. Also the most recent version is v0.2.12 Perhaps try nextflow pull to ensure its up to date. 
```
nextflow pull epi2me-labs/wf-bacterial-genomes
nextflow run epi2me-labs/wf-bacterial-genomes ... rest of your cmd
```

**Comment by sarahjeeeze** [comment]
Closing through lack of response.
